### ISSUE TITLE
无法创建CodeQLpy/out/decode/lib

### ISSUE THREAD

**Issue by Hayashi2026** [webraybtl/CodeQLpy#12]
2023/01/20 00:47:40 functions.py WARNING 
2023/01/20 00:47:40 functions.py WARNING 
Traceback (most recent call last):
  File "/Users/xxx/CodeQL/CodeQLpy/main.py", line 71, in <module>
    createDB(parse_args.target, parse_args.compiled, version, parse_args.jar)
  File "/Users/xxx/CodeQL/CodeQLpy/compiler/database.py", line 402, in createDB
    return createDir(source, compiled, version, jars)
  File "/Users/xxxx/CodeQL/CodeQLpy/compiler/database.py", line 139, in createDir
    compile_cmd = ecjcompile(qlConfig("decode_savedir"), source)
  File "/Users/xxx/CodeQL/CodeQLpy/compiler/ecjcompiler.py", line 98, in ecjcompile
    jar_libs = dirFiles(os.path.join(save_path, "lib"))
  File "/Users/xxx/CodeQL/CodeQLpy/utils/functions.py", line 25, in dirFiles
    for filename in os.listdir(dirpath):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/CodeQL/CodeQLpy/out/decode/lib'

**Comment by webraybtl** [comment]
这是由于源码中没有引入jar包导致的bug，已修复，待测试。
