### ISSUE TITLE
初始化数据库错误

### ISSUE THREAD

**Issue by secxue** [webraybtl/CodeQLpy#30]
python3 main.py -t ***.jar -c

decoding *e.jar...
Command '/Library/Java/JavaVirtualMachines/jdk-11.0.15.jdk/Contents/Home/bin/java -jar lib/jd-cli.jar --outputDir out/decode/xboot-module.jar /***.jar' timed out after 240 seconds
Traceback (most recent call last):
  File "/Users/*/Security/Web/CodeQLpy/main.py", line 75, in <module>
    createDB(parse_args.target, parse_args.compiled, version, parse_args.jar, parse_args.root)
  File "/Users/*/Security/Web/CodeQLpy/compiler/database.py", line 408, in createDB
    return createJar(source, compiled, version)
  File "/Users/*/Security/Web/CodeQLpy/compiler/database.py", line 46, in createJar
    copyJavaFile(java_file, os.path.join(qlConfig("decode_savedir"), "classes"))
  File "/Users/*/Security/Web/CodeQLpy/utils/functions.py", line 77, in copyJavaFile
    with open(srcpath, 'rb') as r:
IsADirectoryError: [Errno 21] Is a directory: 'out/decode/**.jar/META-INF/maven/com.github.spullara.mustache.java'

![image](https://user-images.githubusercontent.com/89639483/226106269-2c79722e-e6e8-4fbd-9016-e046f2974ffc.png)

**Comment by murray-sky** [comment]
雪子，什么时候搞起代审了

**Comment by secxue** [comment]
我日 how are you?
日站遇到的二开系统啊 不想手动看 呜呜

**Comment by webraybtl** [comment]
*.jar这种的正则是错的，应该是seenyong.*.jar这种。你要用正则能匹配到

**Comment by webraybtl** [comment]
*.jar这种的正则是错的，应该是seenyong.*.jar这种。你要用正则能匹配到

**Comment by webraybtl** [comment]
“*.jar”这种是不对的，应该是“seenyon.*.jar”这种，要能正则匹配到的。尽量不要用“.*.jar”，引入其他第三方的jar会出现错误

**Comment by webraybtl** [comment]
星号打不出来，你自己在在线正则里面要能匹配上

**Comment by secxue** [comment]
我这里的* 只是提issue里 待指jar包的名
其实有名字的 
比如test.jar
但是我用你说的..jar还是不行啊

```
python3 main.py -t /Users/test/Downloads/test-3.3.4/test-test/out/artifacts/test/test..jar -c
Welcome to
_______________.___. _________            .___     ________  .____
\______   \__  |   | \_   ___ \  ____   __| _/____ \_____  \ |    |
 |     ___//   |   | /    \  \/ /  _ \ / __ |/ __ \ /  / \  \|    |
 |    |    \____   | \     \___(  <_> ) /_/ \  ___//   \_/.  \    |___
 |____|    / ______|  \______  /\____/\____ |\___  >_____\ \_/_______            \/                \/            \/    \/       \__>       \/

2023/03/20 10:21:42 functions.py WARNING
2023/03/20 10:21:43 functions.py WARNING
2023/03/20 10:21:43 check.py ERROR Target is not exists
 Target Error
```

![image](https://user-images.githubusercontent.com/89639483/226232170-e20bbc7b-f1ce-4f63-8c3f-d105f3bc7c2e.png)

如果是test.jar这种 就是这个issue里 一开始的样子

**Comment by webraybtl** [comment]
大佬，你打码太多，我看不出来了。从这个报错来看，是你的target不存在，或者不是一个正常的目标

**Comment by secxue** [comment]
> 

我打码的就是jar包的路径，按您说的..jar 两个点号 就是不行的，
用一个. 比如test.jar 就是一开始的那个错误
一开始那个我用*或者打码的 是具体的jar包名，因为jar包名不大方便放出 所以我用的*代替的文本 图中打码的
实际上是有这个target的
最后的错误就是那个
```
IsADirectoryError: [Errno 21] Is a directory: 'out/decode/test.jar/META-INF/maven/com.github.spullara.mustache.java'
```

**Comment by murray-sky** [comment]
你这是jar反编译吗，如果是springboot打包的jar包应该没问题，直接打包的把jar包解压后加一个WEB-INF/web.xml文件，可以直接去其他项目里面拷，然后在加上需要反编译的依赖里面的jar包
