### ISSUE TITLE
substring not found

### ISSUE THREAD

**Issue by getcode2git** [webraybtl/CodeQLpy#4]
Traceback (most recent call last):
  File "C:\code\CodeQLpy\main.py", line 71, in <module>
    createDB(parse_args.target, parse_args.compiled, version, parse_args.jar)
  File "C:\code\CodeQLpy\compiler\database.py", line 398, in createDB
    return createDir(source, compiled, version, jars)
  File "C:\code\CodeQLpy\compiler\database.py", line 139, in createDir
    compile_cmd = ecjcompile(qlConfig("decode_savedir"), source)
  File "C:\code\CodeQLpy\compiler\ecjcompiler.py", line 103, in ecjcompile
    source_java_path = getSourcePath(source_path)
  File "C:\code\CodeQLpy\compiler\ecjcompiler.py", line 78, in getSourcePath
    pack_loc = java_file.index(packname.replace(b".", b"/").decode("utf-8"))
ValueError: substring not found

**Comment by webraybtl** [comment]
这主要是由于windows环境和mac环境路径分隔符不同导致的bug，已修复。
